### ISSUE TITLE
uncaught exception in package_augmentation

### ISSUE THREAD

**Issue by miuele** [colcon/colcon-installed-package-information#8]
I was following [the tutorial](https://docs.ros.org/en/iron/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Publisher-And-Subscriber.html), and I encountered the following error.
```
$ colcon build
[0.142s] ERROR:colcon.colcon_core.package_augmentation:Exception in package augmentation extension 'python': 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/package_augmentation/__init__.py", line 97, in augment_packages
    retval = extension.augment_packages(
  File "/usr/lib/python3/dist-packages/colcon_installed_package_information/package_augmentation/python.py", line 44, in augment_packages
    dist = next(iter(dists))
StopIteration
```
I suspect https://github.com/colcon/colcon-installed-package-information/blob/f92c35fddba70680d80902d95f15c84fa93036fb/colcon_installed_package_information/package_augmentation/python.py#L45 `IndexError` should be replaced with `StopIteration`.

I use ROS iron on Ubuntu 22.04.1.
```
$ apt info python3-colcon-core
Package: python3-colcon-core
Version: 0.16.0-1
```

**Comment by MikFerrari** [comment]
The same happened to me and this solved the problem!

**Comment by MatthijsBurgh** [comment]
With the same `0.1.0` -> `0.2.0`, I got another uncaught exception:
```py
[0.281s] ERROR:colcon.colcon_core.package_augmentation:Exception in package augmentation extension 'python': 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/package_augmentation/__init__.py", line 97, in augment_packages
    retval = extension.augment_packages(
  File "/usr/lib/python3/dist-packages/colcon_installed_package_information/package_augmentation/python.py", line 54, in augment_packages
    desc.dependencies['run'].update(
                create_dependency_descriptor(str(req))
                for req in dist.requires)
TypeError: 'NoneType' object is not iterable
```
As dist.requires can also be a `None`:
```py
@property
def requires(self) -> Optional[List[str]]:
    """Generated requirements specified for this Distribution"""
    reqs = self._read_dist_info_reqs() or self._read_egg_info_reqs()
    return reqs and list(reqs)
```
